### ISSUE TITLE
Markdown support?

### ISSUE THREAD

**Issue by virtadpt** [Part-DB/Part-DB-symfony#156]
**Is your feature request related to a problem? Please describe.**
It is not.

**Describe the solution you'd like**
As a user who would like to more easily add his retrogaming recap kits (collections of components for reconditioning and restoring classic computers) to his inventory, it would be helpful to have Markdown support for the Description fields of entries to facilitate listing the components in each kit (e.g., bulleted lists, hyperlinks to documentation pages).

**Describe alternatives you've considered**
I've had success with copy-and-pasting rendered Markdown out of other pages (e.g., https://console5.com/wiki/Atari_XEGS) into Part-DB entries' description fields.  However, it's unwieldly to have to wikify stuff I want to add to my inventory.

**Additional context**
It would have been nice to just type this stuff in with a bulleted list instead of copy-and-pasting:

![Screenshot at 2022-08-02 18-40-03](https://user-images.githubusercontent.com/639730/182505548-21e70d94-e089-41bc-b92a-68a802b5a10d.png)

Are there any particular implementations of Markdown that would work best with Symfony, like Parsedown?

**Comment by jbtronics** [comment]
That behavior is intended, as the description field is currently meant as an single-line (short) description of a part, which can be shown in table views and so on.
If you want to put more detailed information to a part, you should use the comment field, there you have the toolbar with support for lists.

That it currently is possible to insert more than one line is more or less a bug caused by the fact, that you can not configure the editor used, to just accept a single line. I am working on some frontend improvements, and with the new editor this field is really restricted to a single line.

The description field has in theory full markdown support (otherwise your example would not work), but this will make problems when the part is shown in a table view.

**Comment by virtadpt** [comment]
Oh, okay!  That makes a lot of sense, thanks.  I didn't know about the comment field.  I moved the larger blocks of text out of the description and into the comment field and it works great.
