### ISSUE TITLE
How do you enable all the tools? I don't see SMD Reel Rechner and Scanner

### ISSUE THREAD

**Issue by leofabri** [Part-DB/Part-DB-symfony#163]
Hey @jbtronics, I'm trying to enable the tools I see on the Heroku demo app. 
The app is working, but I don't see the Scanner SMD Reel Rechner and the Scanner tools listed in my sidebar. 

Do I need to configure this in some way? Maybe I'm missing something.

I really appreciate any help you can provide. Your hard work is astonishing

**Comment by jbtronics** [comment]
Have you given your user the correct permissions? (You can find that in user or group edit. There is a tools permissions group).
Honestly it just makes sense to enable all permissions, if you are the only user.

Afterwards you should reload the page and the browser and should be able to see it.

That the admin user is missing some permissions after creation is currently a bit ugly and caused by a less than ideal permission system... I currently thinking of some better solutions.
