### ISSUE TITLE
Storage location wrong auto-completion 

### ISSUE THREAD

**Issue by sochartgit** [Part-DB/Part-DB-symfony#412]
**Describe the bug**
If I already have a storage location named and I want to enter a new
storage location in the 'Create new part' window, it automatically fills with existing location.
Example:
  Existing location  14->10 before getting the Create new part window
  Try to create a new storage location:  14->1
  Change focus to quantity, bang  14->10 filled

To bypass that, I have to wait for the + "submenu" to open to create the location manually.

**Comment by jbtronics** [comment]
Do I understand correctly that your problem is that the existing elements are preselected and you have to do an additional click (or arrow up) to creat the new element?
<img width="562" alt="image" src="https://github.com/Part-DB/Part-DB-server/assets/5410681/3748dbd6-892c-48f5-86c6-f6b4a9854221">

I would not call that a bug. In general I would think that the existing elements should be preferred and the creation of a new element is a quite rare task, for which an additonal click is reasonable.
